# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('type', models.CharField(choices=[('New (Whole new)', 'New (Whole new)'), ('Feature', 'Feature'), ('Bug', 'Bug'), ('Release', 'Release'), ('Hot Fix (Bug in Prod)', 'Hot Fix (Bug in Prod)')], max_length=22)),
                ('priority', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=1)),
                ('deadline', models.DateField(auto_now=True)),
            ],
        ),
    ]
